# Generated by Django 5.0.6 on 2024-06-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kalki',
            new_name='Item',
        ),
    ]
